import type { Bill, Budget, Transaction } from './types';

export const CAT_COLORS = [
  /* paleta harmoniosa "Refreshing Aqua Tones" */
  '#0b4f6c', '#12a8de', '#b0f7d4', '#339989', '#7fdc8a',
  '#b3564f', '#bb6b60', '#a8534c', '#c98a5e', '#c1804e', '#d19a72',
  '#d3b869', '#d8c384', '#c1a24c', '#93aa7e', '#74a17c', '#5f9468',
  '#4f9483', '#5aa79b', '#6ba398', '#6f9a97', '#4f8f8f', '#4f9bab',
  '#6b9dc2', '#5687ab', '#7086c4', '#6070a8', '#7c8aa0', '#8391c9',
  '#a480ad', '#93739e', '#8f6bb0', '#ab8bc2', '#c66f8e', '#d087a0',
  '#cf7d8f', '#a3566a', '#93715f', '#83614f', '#78899a', '#8b9198',
];

export const DEMO_TRANSACTIONS: Transaction[] = [
  {
    id: 'demo-9001',
    user_id: 'demo',
    type: 'out',
    description: 'Supermercado Pão de Açúcar',
    amount: 187.4,
    category: 'Alimentação',
    color: '#bb6b60',
    occurred_on: '2026-08-15',
    recurring: false,
    parent_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-9002',
    user_id: 'demo',
    type: 'out',
    description: '99 Táxi',
    amount: 24.0,
    category: 'Transporte',
    color: '#6b9dc2',
    occurred_on: '2026-08-15',
    recurring: false,
    parent_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-9003',
    user_id: 'demo',
    type: 'in',
    description: 'Empresa · folha salarial',
    amount: 6200.0,
    category: 'Salário',
    color: '#4f9483',
    occurred_on: '2026-08-14',
    recurring: false,
    parent_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-9004',
    user_id: 'demo',
    type: 'out',
    description: 'Condomínio Ed. Ipê',
    amount: 620.0,
    category: 'Moradia',
    color: '#93739e',
    occurred_on: '2026-08-14',
    recurring: false,
    parent_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-9005',
    user_id: 'demo',
    type: 'out',
    description: 'Cinemark',
    amount: 68.0,
    category: 'Lazer',
    color: '#c66f8e',
    occurred_on: '2026-08-14',
    recurring: false,
    parent_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-9006',
    user_id: 'demo',
    type: 'out',
    description: 'Netflix',
    amount: 44.9,
    category: 'Assinaturas',
    color: '#d3b869',
    occurred_on: '2026-08-10',
    recurring: true,
    parent_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-9007',
    user_id: 'demo',
    type: 'out',
    description: 'Spotify',
    amount: 21.9,
    category: 'Assinaturas',
    color: '#d3b869',
    occurred_on: '2026-08-12',
    recurring: true,
    parent_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-9008',
    user_id: 'demo',
    type: 'out',
    description: 'Farmácia São João',
    amount: 56.3,
    category: 'Saúde',
    color: '#74a17c',
    occurred_on: '2026-08-08',
    recurring: false,
    parent_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-9009',
    user_id: 'demo',
    type: 'out',
    description: 'Posto Ipiranga',
    amount: 150.0,
    category: 'Transporte',
    color: '#6b9dc2',
    occurred_on: '2026-08-05',
    recurring: false,
    parent_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-9010',
    user_id: 'demo',
    type: 'out',
    description: 'iFood',
    amount: 62.5,
    category: 'Alimentação',
    color: '#bb6b60',
    occurred_on: '2026-08-03',
    recurring: false,
    parent_id: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-9011',
    user_id: 'demo',
    type: 'in',
    description: 'Freelance design',
    amount: 850.0,
    category: 'Outros',
    color: '#8b9198',
    occurred_on: '2026-08-02',
    recurring: false,
    parent_id: null,
    created_at: new Date().toISOString(),
  },
];

export const DEMO_BILLS: Bill[] = [
  {
    id: 'demo-9101',
    user_id: 'demo',
    description: 'Cartão · Nubank',
    category: 'Outros',
    color: '#8b9198',
    amount: 1340.55,
    due_date: '2026-08-22',
    status: 'due',
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-9102',
    user_id: 'demo',
    description: 'Energia · Enel',
    category: 'Moradia',
    color: '#93739e',
    amount: 214.9,
    due_date: '2026-08-18',
    status: 'due',
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-9103',
    user_id: 'demo',
    description: 'Internet · Vivo Fibra',
    category: 'Moradia',
    color: '#93739e',
    amount: 99.9,
    due_date: '2026-08-20',
    status: 'due',
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-9104',
    user_id: 'demo',
    description: 'IPTU · parcela 8/10',
    category: 'Moradia',
    color: '#93739e',
    amount: 156.0,
    due_date: '2026-08-10',
    status: 'due',
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-9105',
    user_id: 'demo',
    description: 'Academia · Smart Fit',
    category: 'Saúde',
    color: '#74a17c',
    amount: 109.9,
    due_date: '2026-08-05',
    status: 'paid',
    created_at: new Date().toISOString(),
  },
];

export const DEMO_BUDGETS: Budget[] = [
  { user_id: 'demo', category: 'Alimentação', amount: 700, color: '#bb6b60', updated_at: new Date().toISOString() },
  { user_id: 'demo', category: 'Moradia', amount: 1200, color: '#93739e', updated_at: new Date().toISOString() },
  { user_id: 'demo', category: 'Transporte', amount: 350, color: '#6b9dc2', updated_at: new Date().toISOString() },
  { user_id: 'demo', category: 'Lazer', amount: 250, color: '#c66f8e', updated_at: new Date().toISOString() },
];
